export const SYMBOLS = {
  SQS_DECORATOR_ERROR_HANDLER: Symbol.for('SQS_DECORATOR_ERROR_HANDLER'),
  SQS_DECORATOR_CONSUMER_METHOD: Symbol.for('SQS_DECORATOR_CONSUMER_METHOD'),
  SQS_SERVICE: Symbol.for('SQS_SERVICE'),
  SQS_MODULE_CONFIGURATION: Symbol.for('SQS_MODULE_CONFIGURATION'),
  SQS_MODULE_FOR_FEATURE_CONFIGURATION: Symbol.for('SQS_MODULE_FOR_FEATURE_CONFIGURATION'),
  SQS_CLIENT: Symbol.for('SQS_CLIENT'),
  SQS_QUEUES_SERVICE: Symbol.for('SQS_QUEUES_SERVICE'),
  SQS_HANDLER_DISCOVERY_SERVICE: Symbol.for('SQS_HANDLER_DISCOVERY_SERVICE'),
  SQS_HANDLERS_MANAGER: Symbol.for('SQS_HANDLERS_MANAGER'),
  SQS_HANDLER_REGISTER_SERVICE: Symbol.for('SQS_HANDLER_REGISTER_SERVICE'),
};
